### ISSUE TITLE
Form don't add input field [Partial complete]

### ISSUE THREAD

**Issue by SSirjes** [Voog/design-zurich#11]
Common page two column, common page: form don't add new input field. 
In front page form works.

Front page: input field "extra property" box location is away from input field
![screen shot 2015-10-23 at 09 56 26](https://cloud.githubusercontent.com/assets/13623224/10686396/6497a37a-796c-11e5-9694-f99ad34e2021.png)

**Comment by otttooming** [comment]
Form modal box location behavior is observed to behave consistently with other Voog templates.
