### ISSUE TITLE
Search form results box is out of container

### ISSUE THREAD

**Issue by SSirjes** [Voog/design-zurich#12]
1. Front page: if search form is under menu and aligned left then search result's are out of container: 
   ![screen shot 2015-10-23 at 10 29 38](https://cloud.githubusercontent.com/assets/13623224/10686928/b8bbef06-7971-11e5-8b3c-74bf7e079400.png)
2. search sentence and search icon are too bottom
   ![screen shot 2015-10-23 at 10 50 39](https://cloud.githubusercontent.com/assets/13623224/10687211/f3d659d0-7973-11e5-965e-a9ba76745dfe.png)

**Comment by otttooming** [comment]
Fixed in 0ea28b9
