### ISSUE TITLE
Common page two column: right box and submenu differences

### ISSUE THREAD

**Issue by SSirjes** [Voog/design-zurich#13]
Without submenu:
![screen shot 2015-10-23 at 13 50 20](https://cloud.githubusercontent.com/assets/13623224/10691148/a7f29472-798f-11e5-934a-5ba2bae2e170.png)

With submenu:
![screen shot 2015-10-23 at 13 52 10](https://cloud.githubusercontent.com/assets/13623224/10691152/b58e560c-798f-11e5-8f15-031daa4d65e9.png)

**Comment by otttooming** [comment]
Related to Bern template behavior. Needs clarification for desired behavior from Bern development.

**Comment by kaspar-naaber** [comment]
I updated both – Bern and Zürich and fixed the issue.
