### ISSUE TITLE
h1 has different font-size and line-height as in front page

### ISSUE THREAD

**Issue by SSirjes** [Voog/design-zurich#15]
![screen shot 2015-10-23 at 15 48 04](https://cloud.githubusercontent.com/assets/13623224/10693212/8559bf98-799f-11e5-810e-b3a1a26a14fb.png)

Front page
![screen shot 2015-10-23 at 16 05 04](https://cloud.githubusercontent.com/assets/13623224/10693285/edd3c898-799f-11e5-8e9e-d97cd0c2fa94.png)

**Comment by otttooming** [comment]
Design requirement for front page specific visual style. Common with other Voog templates.
