### ISSUE TITLE
Mobile menu: language menu don't link properly

### ISSUE THREAD

**Issue by SSirjes** [Voog/design-zurich#16]
Sometimes when I want to change language, then mobile language menu don't link to current language page. Menu item only remains active and stays to mobile menu view.

**Comment by otttooming** [comment]
Can't seem to replicate the issue on iPhone, iPad (iOS 9) or Windows 10 tablet. Probably fixed.

**Comment by SSirjes** [comment]
Like Ott already mentioned:
"Can't seem to replicate the issue on iPhone, iPad (iOS 9) or Windows 10 tablet. Probably fixed."
