### ISSUE TITLE
Firefox bg-picker: choosing bg color and changing opacity don't work

### ISSUE THREAD

**Issue by SSirjes** [Voog/design-zurich#18]
Bg-picker: 
1. choose background color; 
2. change opacity. Now when I drag opacity back to 100% it sets background color always to white.

**Comment by otttooming** [comment]
Related to Voog CMS BG picker issue.

Steps to reproduce:
- Select color
- Slide opacity to 0
- Color value is reset and opacity slider is not working anymore.

Expected behaviour:
Color value should be rgba(x,x,x,0) if slider is at 0.
