### ISSUE TITLE
Front page: square gallery put some free space to image top

### ISSUE THREAD

**Issue by SSirjes** [Voog/design-zurich#21]
![screen shot 2015-11-02 at 09 21 58](https://cloud.githubusercontent.com/assets/13623224/10876201/3d71858e-8143-11e5-9c91-93c6d93fb088.png)

**Comment by otttooming** [comment]
Related to behavior from edicy-gallery.css, which applies margin: 2px to all a.edys-gallery-item's. Fix probably not recommended from template side.
