### ISSUE TITLE
Menu: active menu item is not so good standing out

### ISSUE THREAD

**Issue by SSirjes** [Voog/design-zurich#25]
Also submenu active item is darker inversely main menu active item. 

Here is active "Product" and "alamleht 2":
![screen shot 2015-11-04 at 09 57 54](https://cloud.githubusercontent.com/assets/13623224/10932690/792545c2-82db-11e5-9f51-6d87025147f9.png)

**Comment by otttooming** [comment]
Current behavior is consistent with Bern template front page form lightness styles. Common page layout has multiple separate stylistic outputs. Any change needs to be consulted with the designer for the desired outcome.

**Comment by otttooming** [comment]
Visual change related to Bern template commonality, needs design input and authorization to apply changes.

**Comment by SSirjes** [comment]
Menu items should have font-weight:600, like Bern.
