### ISSUE TITLE
Implement Kaufhaus

### ISSUE THREAD

**Issue by kaspar-naaber** [Voog/design-zurich#68]
(Pull request: #71)
~~Can be found in master branch.~~

**Comment by SSirjes** [comment]
@kaspar-naaber:
> The following is not relevant anymore.

~~On smaller screen shopping cart button and language menu overlaps. Video: http://recordit.co/DLrw55uiaj~~

![screen shot 2016-10-19 at 13 21 43](https://cloud.githubusercontent.com/assets/13623224/19515263/5933faf0-95ff-11e6-8b7c-b50e42c1afd1.png)

~~At some point search, language menu and shopping cart button overlap each other. Video: http://recordit.co/S0DOFMjxuR~~

![screen shot 2016-10-19 at 13 35 18](https://cloud.githubusercontent.com/assets/13623224/19515625/eb0ae208-9600-11e6-9e4c-d086ac5e21e0.png)
