### ISSUE TITLE
Different form color

### ISSUE THREAD

**Issue by SSirjes** [Voog/design-zurich#7]
Blog page and front page form has different input color if background is set white.

Blog:
![screen shot 2015-10-22 at 11 00 01](https://cloud.githubusercontent.com/assets/13623224/10659965/5abcf866-78ac-11e5-90e2-74a9c34c10a7.png)

Front page:
![screen shot 2015-10-22 at 11 00 33](https://cloud.githubusercontent.com/assets/13623224/10659966/5abe004e-78ac-11e5-9e0f-2717fbe62f99.png)

**Comment by SSirjes** [comment]
Front page background color is white. Drag form to front page into text block. Form input background color is very dark. 

![screen shot 2015-10-30 at 15 30 11](https://cloud.githubusercontent.com/assets/13623224/10846833/2baa2e48-7f1b-11e5-8aa2-e07772e0d508.png)

**Comment by otttooming** [comment]
Current behavior is consistent with Bern template front page form lightness styles. Common page layout has multiple separate stylistic outputs. Any change needs to be consulted with the designer for the desired outcome.

**Comment by SSirjes** [comment]
Front page: form checkboxes and single choice background color are white 
![screen shot 2015-11-10 at 13 56 47](https://cloud.githubusercontent.com/assets/13623224/11061923/37c46f40-87b3-11e5-89b1-90476736e964.png)
